apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecret.secretStoreRef.name }}
  namespace: {{ .Values.externalSecret.namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.externalSecret.secretStoreRef.region }}
      auth:
        serviceAccountRef:
          name: {{ .Values.serviceAccount.externalSecrets.name }}
