apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::976552365380:role/karpenter-eks-node-group-20240820074628272500000001
