name: Helm Chart Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install -g semantic-release @semantic-release/github @semantic-release/git
          rm -rf node_modules
          npm install

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release

      - name: Package Helm Charts
        run: |
          helm package ./charts --destination ./charts/packages

      - name: Index Helm Charts
        run: |
          helm repo index ./charts/packages --url https://<your-github-username>.github.io/helm-charts/

      - name: Deploy to GitHub Pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git clone --branch gh-pages https://github.com/${{ github.repository }} gh-pages
          cd gh-pages
          rm -rf *
          cp -R ../charts/packages/* .
          git add .
          git commit -m "Update Helm chart index and packages"
          git push
